//
// Created by Vital Vinahradau on 3/16/18.
// Copyright (c) 2018 ___VITAL___. All rights reserved.
//

import Foundation

public enum Language: String, Codable {
    case ar // "Arabic"
    case bg // "Bulgarian"
    case bn // "Bengali"
    case ca // "Catalan"
    case cs // "Czech"
    case da // "Danish"
    case de // "German"
    case el // "Greek"
    case en // "English"
    case enAU = "en-AU" // "English (Australian)"
    case enGB = "en-GB" // "English (Great Britain)"
    case es // "Spanish"
    case eu // "Basque"
    case fa // "Farsi"
    case fi // "Finnish"
    case fil // "Filipino"
    case fr // "French"
    case gl // "Galician"
    case gu // "Gujarati"
    case hi // "Hindi"
    case hr // "Croatian"
    case hu // "Hungarian"
    case id // "Indonesian"
    case it // "Italian"
    case iw // "Hebrew"
    case ja // "Japanese"
    case kn // "Kannada"
    case ko // "Korean"
    case lt // "Lithuanian"
    case lv // "Latvian"
    case ml // "Malayalam"
    case mr // "Marathi"
    case nl // "Dutch"
    case no // "Norwegian"
    case pl // "Polish"
    case pt // "Portuguese"
    case ptBR = "pt-BR" // "Portuguese (Brazil)"
    case ptPT = "pt-PT" // "Portuguese (Portugal)"
    case ro // "Romanian"
    case ru // "Russian"
    case sk // "Slovak"
    case sl // "Slovenian"
    case sr // "Serbian"
    case sv // "Swedish"
    case ta // "Tamil"
    case te // "Telugu"
    case th // "Thai"
    case tl // "Tagalog"
    case tr // "Turkish"
    case uk // "Ukrainian"
    case vi // "Vietnamese"
    case zhCN = "zh-CN" // "Chinese (Simplified)"
    case zhTW = "zh-TW" // "Chinese (Traditional)"
}
